name: Label Sync

on:
  push:
    branches:
      - "main"
    paths:
      - ".github/workflows/label-sync.yml"
      - ".github/labels.yml"
  workflow_dispatch:

jobs:
  sync-labels:
    name: Sync labels
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          sparse-checkout: .github/labels.yml

      - name: Sync labels
        uses: EndBug/label-sync@v2
        with:
          config-file: .github/labels.yml
          token: ${{ secrets.GITHUB_TOKEN }}
          delete-other-labels: true
